=== emilycb97/moje-portfolio-web/partials/kpop/idols.dtd
<!ENTITY hight "cm">
<!ENTITY USD "USD">
<!ENTITY KRW "KRW">
<!ENTITY % addressElements "street, district, city, country">

<!ELEMENT kpopIdols (metadata?, groups, idols, agencies, positions)>

<!--groups-->
<!ELEMENT groups (group+)>
<!ELEMENT group (nameG, difName?, gender, fandom, member, inAgency, websiteG?, instagramG?, twitterX*, tiktok?, youtube?, spotify?)>
<!ATTLIST group
        IDG ID #REQUIRED
        numberOfMembers CDATA #REQUIRED
        dateOfDebut NMTOKEN #REQUIRED>
<!ELEMENT nameG (#PCDATA)>
<!ELEMENT difName (#PCDATA)>
<!ELEMENT gender EMPTY>
<!ATTLIST gender whatGender (boys | girls | mixed) #REQUIRED>
<!ELEMENT fandom (#PCDATA)>
<!ELEMENT member EMPTY>
<!ATTLIST member IDRefM IDREFS #REQUIRED>
<!ELEMENT inAgency EMPTY>
<!ATTLIST inAgency IDRefA IDREFS #REQUIRED>
<!ELEMENT websiteG (#PCDATA)>
<!ELEMENT instagramG (#PCDATA)>
<!ELEMENT twitterX (#PCDATA)>
<!ELEMENT tiktok (#PCDATA)>
<!ELEMENT youtube (#PCDATA)>
<!ELEMENT spotify (#PCDATA)>

<!--idols-->
<!ELEMENT idols (idol+)>
<!ELEMENT idol (stageName, nameI+, surname+, inGroup, whatPosition, height, zodiacSign, mbti, nationality+, instagram*)>
<!ATTLIST idol
        IDI ID #REQUIRED
        dateOfBirth CDATA #REQUIRED>
<!ELEMENT nameI (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT stageName (#PCDATA)>
<!ELEMENT inGroup EMPTY>
<!ATTLIST inGroup IDRefG IDREF #REQUIRED>
<!ELEMENT whatPosition EMPTY>
<!ATTLIST whatPosition IDRefP IDREFS #REQUIRED>
<!ELEMENT height (#PCDATA)>
<!ATTLIST height
        unit (cm | m | in | ft) #REQUIRED>
<!ELEMENT zodiacSign (#PCDATA)>
<!ATTLIST zodiacSign
        type (Aries | Taurus | Gemini | Cancer | Leo | Virgo | Libra | Scorpio | Sagittarius | Capricorn | Aquarius | Pisces) #IMPLIED>
<!ELEMENT mbti (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT instagram (#PCDATA)>

<!--agencies-->
<!ELEMENT agencies (agency+)>
<!ELEMENT agency (nameA, address, founder, phoneNumber?, email+, websiteA, revenue+)>
<!ATTLIST agency
        IDA ID #REQUIRED
        yearOfFounding CDATA #REQUIRED>
<!ELEMENT nameA (#PCDATA)>
<!ELEMENT address (%addressElements;)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT district (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT founder (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT websiteA (#PCDATA)>
<!ELEMENT revenue (#PCDATA)>
<!ATTLIST revenue
        currency (USD | KRW | EUR) #REQUIRED
        unit (billions | trillions | millions) #REQUIRED>

<!--positions-->
<!ELEMENT positions (position+)>
<!ELEMENT position (#PCDATA)>
<!ATTLIST position
        IDP ID #REQUIRED>

<!--metdata-->
<!ELEMENT metadata (author+, modificationDate)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT modificationDate (#PCDATA)>

=== emilycb97/moje-portfolio-web/partials/kpop/kpopIdols.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css" ?>
<!DOCTYPE kpopIdols SYSTEM "idols.dtd">

<kpopIdols>

    <metadata>
        <author>Emilia Szczerba</author>
        <modificationDate>2024-11-17</modificationDate>
    </metadata>

    <groups>
        <group IDG="G01" numberOfMembers="8" dateOfDebut="25-03-2018">
            <nameG>Stray Kids</nameG>
            <difName>SKZ</difName>
            <gender whatGender="boys"/>
            <fandom>STAY</fandom>
            <member IDRefM="I01 I02 I03 I04 I05 I06 I07 I08"/>
            <inAgency IDRefA="A1"/>
            <websiteG>https://straykids.jype.com</websiteG>
            <instagramG>@realstraykids</instagramG>
            <twitterX>@Stray_Kids</twitterX>
            <tiktok>@jypestraykids</tiktok>
            <youtube>https://www.youtube.com/@StrayKids</youtube>
            <spotify>https://open.spotify.com/artist/2dIgFjalVxs4ThymZ67YCE?si=g8HfRS9XQkGqD8kzH_0oJw</spotify>
        </group>

        <group IDG="G02" numberOfMembers="5" dateOfDebut="04-03-2019">
            <nameG>TOMORROW X TOGETHER</nameG>
            <difName>TXT</difName>
            <gender whatGender="boys"/>
            <fandom>MOA</fandom>
            <member IDRefM="I09 I10 I11 I12 I13"/>
            <inAgency IDRefA="A2"/>
            <websiteG>https://ibighit.com/txt/eng/</websiteG>
            <instagramG>@txt_bighit</instagramG>
            <twitterX>@TXT_bighit</twitterX>
            <twitterX>@TXT_members</twitterX>
            <tiktok>@txt.bighitent</tiktok>
            <youtube>https://www.youtube.com/txt_bighit</youtube>
            <spotify>https://open.spotify.com/artist/0ghlgldX5Dd6720Q3qFyQB?si=xIEYEasTQd6zzhntK2_Z7A</spotify>
        </group>

        <group IDG="G03" numberOfMembers="7" dateOfDebut="13-06-2013">
            <nameG>BTS</nameG>
            <difName>Bangtan Boys</difName>
            <gender whatGender="boys"/>
            <fandom>A.R.M.Y</fandom>
            <member IDRefM="I14 I15 I16 I17 I18 I19 I20"/>
            <inAgency IDRefA="A2"/>
            <websiteG>https://ibighit.com/bts/eng/</websiteG>
            <instagramG>@bts.bighitofficial</instagramG>
            <twitterX>@bts_twt</twitterX>
            <tiktok>@bts_official_bighit</tiktok>
            <youtube>https://www.youtube.com/channel/UCLkAepWjdylmXSltofFvsYQ</youtube>
            <spotify>https://open.spotify.com/artist/3Nrfpe0tUJi4K4DXYWgMUX?si=0EaNnek3QZSfa3hZB_csMA</spotify>
        </group>

        <group IDG="G04" numberOfMembers="4" dateOfDebut="17-11-2020">
            <nameG>aespa</nameG>
            <gender whatGender="girls"/>
            <fandom>MY</fandom>
            <member IDRefM="I21 I22 I23 I24"/>
            <inAgency IDRefA="A3"/>
            <websiteG>https://www.aespa.com</websiteG>
            <instagramG>@aespa_official</instagramG>
            <twitterX>@aespa_official</twitterX>
            <tiktok>@aespa_official</tiktok>
            <youtube>https://www.youtube.com/c/aespa</youtube>
            <spotify>https://open.spotify.com/artist/6YVMFz59CuY7ngCxTxjpxE?si=ymdymfAnQpyfiizfv8iDEg</spotify>
        </group>

        <group IDG="G05" numberOfMembers="4" dateOfDebut="19-06-2017">
            <nameG>KARD</nameG>
            <difName>K.A.R.D</difName>
            <gender whatGender="mixed"/>
            <fandom>Hidden Kard</fandom>
            <member IDRefM="I25 I26 I27 I28"/>
            <inAgency IDRefA="A4"/>
            <websiteG>https://www.kard.kr</websiteG>
            <instagramG>@official_kard</instagramG>
            <twitterX>@KARD_Official</twitterX>
            <tiktok>@official.kard</tiktok>
            <youtube>https://www.youtube.com/channel/UC5OwlwvsVmf_lXHguB6OYFw</youtube>
            <spotify>https://open.spotify.com/artist/2JhAlkmukNvarUpGhTFXUQ?si=Lw7XPY7eQ-ak2CuH4IiZUQ</spotify>
        </group>

    </groups>

    <idols>
        <idol IDI="I01" dateOfBirth="03-10-1997">
            <stageName>Bang Chan</stageName>
            <nameI>Christopher</nameI>
            <nameI>Chahn</nameI>
            <surname>Bahng</surname>
            <inGroup IDRefG="G01"/>
            <whatPosition IDRefP="P1 P2 P3 P4 P5"/>
            <height unit="cm">172</height>
            <zodiacSign>Libra</zodiacSign>
            <mbti>ENFJ</mbti>
            <nationality>Australian</nationality>
            <nationality>South Korean</nationality>
            <instagram>@gnabnahc</instagram>
        </idol>

        <idol IDI="I02" dateOfBirth="25-10-1998">
            <stageName>Lee Know</stageName>
            <nameI>Minho</nameI>
            <surname>Lee</surname>
            <inGroup IDRefG="G01"/>
            <whatPosition IDRefP="P2 P4 P5"/>
            <height unit="cm">172</height>
            <zodiacSign>Scorpio</zodiacSign>
            <mbti>ISFP</mbti>
            <nationality>South Korean</nationality>
            <instagram>@t.leeknowsaurus</instagram>
        </idol>

        <idol IDI="I03" dateOfBirth="11-08-1999">
            <stageName>Changbin</stageName>
            <nameI>Changbin</nameI>
            <surname>Seo</surname>
            <inGroup IDRefG="G01"/>
            <whatPosition IDRefP="P2 P3 P4"/>
            <height unit="cm">167</height>
            <zodiacSign>Leo</zodiacSign>
            <mbti>ESTP</mbti>
            <nationality>South Korean</nationality>
            <instagram>@jutdwae</instagram>
        </idol>

        <idol IDI="I04" dateOfBirth="20-03-2000">
            <stageName>Hyunjin</stageName>
            <nameI>Hyunjin</nameI>
            <surname>Hwang</surname>
            <inGroup IDRefG="G01"/>
            <whatPosition IDRefP="P2 P4 P5 P6"/>
            <height unit="cm">179</height>
            <zodiacSign>Pisces</zodiacSign>
            <mbti>ESTP</mbti>
            <nationality>South Korean</nationality>
            <instagram>@hynjinnnn</instagram>
        </idol>

        <idol IDI="I05" dateOfBirth="14-09-2000">
            <stageName>Han</stageName>
            <nameI>Jisung</nameI>
            <surname>Han</surname>
            <inGroup IDRefG="G01"/>
            <whatPosition IDRefP="P2 P3 P4"/>
            <height unit="cm">169</height>
            <zodiacSign>Virgo</zodiacSign>
            <mbti>ISTP</mbti>
            <nationality>South Korean</nationality>
            <instagram>@_doolsetnet</instagram>
        </idol>

        <idol IDI="I06" dateOfBirth="15-09-2000">
            <stageName>Felix</stageName>
            <nameI>Felix</nameI>
            <nameI>Yongbok</nameI>
            <surname>Lee</surname>
            <inGroup IDRefG="G01"/>
            <whatPosition IDRefP="P2 P4 P5"/>
            <height unit="cm">171</height>
            <zodiacSign>Virgo</zodiacSign>
            <mbti>ENFJ</mbti>
            <nationality>South Korean</nationality>
            <nationality>Australian</nationality>
            <instagram>@yong.lixx</instagram>
        </idol>

        <idol IDI="I07" dateOfBirth="22-09-2000">
            <stageName>Seungmin</stageName>
            <nameI>Seungmin</nameI>
            <surname>Kim</surname>
            <inGroup IDRefG="G01"/>
            <whatPosition IDRefP="P4"/>
            <height unit="cm">178</height>
            <zodiacSign>Virgo</zodiacSign>
            <mbti>ISFJ</mbti>
            <nationality>South Korean</nationality>
            <instagram>@miniverse.__</instagram>
        </idol>

        <idol IDI="I08" dateOfBirth="08-02-2001">
            <stageName>I.N</stageName>
            <nameI>Jeongin</nameI>
            <surname>Yang</surname>
            <inGroup IDRefG="G01"/>
            <whatPosition IDRefP="P4"/>
            <height unit="cm">172</height>
            <zodiacSign>Aquarius</zodiacSign>
            <mbti>INFJ</mbti>
            <nationality>South Korean</nationality>
            <instagram>@i.2.n.8</instagram>
        </idol>

        <idol IDI="I09" dateOfBirth="05-12-2000">
            <stageName>Soobin</stageName>
            <nameI>Soobin</nameI>
            <surname>Choi</surname>
            <inGroup IDRefG="G02"/>
            <whatPosition IDRefP="P1"/>
            <height unit="cm">185</height>
            <zodiacSign>Sagittarius</zodiacSign>
            <mbti>ISFP</mbti>
            <nationality>South Korean</nationality>
            <instagram>@page.soobin</instagram>
        </idol>

        <idol IDI="I10" dateOfBirth="13-09-1999">
            <stageName>Yeonjun</stageName>
            <nameI>Yeonjun</nameI>
            <surname>Choi</surname>
            <inGroup IDRefG="G02"/>
            <whatPosition IDRefP="P2 P5 P6"/>
            <height unit="cm">182</height>
            <zodiacSign>Virgo</zodiacSign>
            <mbti>ENFP</mbti>
            <nationality>South Korean</nationality>
            <instagram>@yawnzzn</instagram>
        </idol>

        <idol IDI="I11" dateOfBirth="13-03-2001">
            <stageName>Beomgyu</stageName>
            <nameI>Beomgyu</nameI>
            <surname>Choi</surname>
            <inGroup IDRefG="G02"/>
            <whatPosition IDRefP="P6"/>
            <height unit="cm">180</height>
            <zodiacSign>Pisces</zodiacSign>
            <mbti>ISFJ</mbti>
            <nationality>South Korean</nationality>
            <instagram>@bamgyuuuu</instagram>
        </idol>

        <idol IDI="I12" dateOfBirth="05-02-2002">
            <stageName>Taehyun</stageName>
            <nameI>Taehyun</nameI>
            <surname>Kang</surname>
            <inGroup IDRefG="G02"/>
            <whatPosition IDRefP="P4"/>
            <height unit="cm">177</height>
            <zodiacSign>Aquarius</zodiacSign>
            <mbti>ESTP</mbti>
            <nationality>South Korean</nationality>
        </idol>

        <idol IDI="I13" dateOfBirth="14-08-2002">
            <stageName>Huening Kai</stageName>
            <nameI>Kai</nameI>
            <nameI>Kamal</nameI>
            <surname>Huening</surname>
            <inGroup IDRefG="G02"/>
